### ISSUE TITLE
custom properties are getting lost 

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-adroll#1]
_From @chiplay on April 10, 2015 15:38_

Right now, custom track properties are sent as a generic object attached to `adroll_custom_data` like so: `if (!is.empty(customProps)) data.adroll_custom_data = customProps;`

But `order_id` and `user_id` are plucked out and attached directly to the `data` object passed to `window.__adroll.record_user(data);` Then the `record_user` method in AdRoll's library picks out the bits they want, eg. adroll_segments, adroll_conversion_value_in_dollars, and pass all the rest of the key/vals of that data object into there own internal `adroll_custom_data` object.  Which leaves you with something like:

```
adroll_custom_data: {
  order_id: GUID,
  user_id: GUID,
  adroll_custom_data: {
    someOtherProp: val
  }
}
```

and the `adroll_custom_data` is lost when sent over the wire to Adroll in the pixel url: `&adroll_custom_data%3D%5Bobject%20Object%5D`

Here is the `record_user` method for reference:

```
record_user: function(a) {
      var d = ["adroll_conversion_value", "adroll_conversion_value_in_dollars", "adroll_segments", "adroll_email", "adroll_currency"], c, e;
      a = a || {};
      var f = {adroll_email: !0};
      for (c = 0; c < d.length; c++) {
        try {
          delete b[d[c]]
        } catch (g) {
        }
        if (d[c] in a) {
          b[d[c]] = d[c] in f ? b.escape(a[d[c]]) : a[d[c]];
          try {
            delete a[d[c]]
          } catch (j) {
          }
        }
      }
      try {
        delete b.adroll_custom_data
      } catch (k) {
      }
      for (e in a)
        if (a.hasOwnProperty(e)) {
          b.adroll_custom_data = a;
          break
        }
      this.render_pixel_code(b.adroll_adv_id, 
      b.adroll_pix_id)
    },
```

I propose iterating over the other custom props, snaking each key, and attaching them directly to the data object like so:

```
if (!is.empty(customProps)) {
  each(customProps, function(key, val) {
    data[snake(key)] = val;
  });
}
```

Thoughts?

_Copied from original issue: segmentio/analytics.js-integrations#588_

**Comment by ndhoule** [comment]
_From @sperand-io on April 17, 2015 17:56_

hey @chiplay, great catch! confirmed — this is a bug. will try to get this fix out early next week!

**Comment by camsjams** [comment]
I am still seeing this issue as well - any news on the potential fix?

`adroll_custom_data=%5Bobject%20Object%5D`

**Comment by camsjams** [comment]
For other developers, I would note that I am able to accomplish it using this method, and the library will automatically map to `adroll_external_data` :

```
var $premiumCompMod =$(..);
__adroll.record_user(
    {
        'adroll_segments': 'xxxx',
        'adroll_conversion_value': $premiumCompMod.data('planPrice'),
        'adroll_currency': $premiumCompMod.data('planCurrencyCode'),
        'YOUR_CUSTOM_DATA_KEY': 'YOUR_CUSTOM_DATA_VALUE'
    }
);
```

**Comment by sperand-io** [comment]
fixed here https://github.com/segment-integrations/analytics.js-integration-adroll/pull/3
