### ISSUE TITLE
adroll: add segmentation based on .identify() traits

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-adroll#2]
_From @reinpk on July 3, 2014 7:45_

would need to be spec'd out a bit with how to send this to adroll, but similar to the track call potentially:
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/adroll/index.js#L121

_Copied from original issue: segmentio/analytics.js-integrations#326_

**Comment by ndhoule** [comment]
_From @j0rd on October 29, 2014 13:34_

Will require something like this as well...but I think it might be done.

```
AdRoll.prototype.track = function(track){
  var event = track.event();
  var user = this.analytics.user();
  var events = this.events(event);
  var total = track.revenue() || track.total() || 0;
  var orderId = track.orderId() || 0;

  each(events, function(event){
    var data = {};
    if (user.id()) data.user_id = user.id();
    data.adroll_conversion_value_in_dollars = total;
    data.order_id = orderId;
    // the adroll interface only allows for
    // segment names which are snake cased.
    data.adroll_segments = snake(event);
    window.__adroll.record_user(data);
  });

  // no events found
  if (!events.length) {
    var data = {};
    if (user.id()) data.user_id = user.id();
    data.adroll_segments = snake(event);
    window.__adroll.record_user(data);
  }
};
```

Notice:
**data.adroll_segments = snake(event);**

This is how adroll asks you to segment your users on the client side

```
try { __adroll.record_user({"adroll_segments": "segment_name"}) } catch(err) {}
```

Seems to be in the "track" code, so perhaps this is done.

**Comment by hankim813** [comment]
no longer supported by Adroll

https://github.com/segment-integrations/analytics.js-integration-intercom/blob/master/lib/index.js#L99-L104
