### ISSUE TITLE
Variables for Conversion tracking have been updated in new builds of AdRoll Smart Pixel

### ISSUE THREAD

**Issue by jgilladroll** [segment-integrations/analytics.js-integration-adroll#4]
https://help.adroll.com/hc/en-us/articles/212629938-Setting-Up-Enhanced-Conversion-Tracking

adroll_conversion_value_in_dollars is now adroll_conversion_value.
Also we now have a variable "adroll_currency" which follows the ISO-4217 format to differentiate between different currency markets.

**Comment by hankim813** [comment]
@jgilladroll Thanks for the heads up here. I've added this to our list of integrations to update. Unless you want to submit a PR ;)

**Comment by hankim813** [comment]
@jgilladroll fyi -- updating these won't have any backward compat issues? So mutual clients will not have any breaking reports because they updated the `adroll_conversion_value_in_dollars` to `adroll_conversion_value` correct?
